# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Coursework
    url: content/
    weight: 40    
  - name: Discussions
    url: coursework/discussions/
    weight: 41
    parent: Coursework

  - name: Kritik Creations
    url: coursework/kritik-creations/
    weight: 42
    parent: Coursework

  - name: Individual Assignments
    url: coursework/individual-assignments/
    weight: 43
    parent: Coursework

  - name: Group Assignments
    url: coursework/group-assignments/
    weight: 44
    parent: Coursework